version: '3'

services:
  drill-admin:
    image: drill4j/admin:0.5.0-130
    environment:
      - TEST2CODE_PLUGIN_VERSION=0.5.0-128
      - LOG_LEVEL=INFO
    ports:
      - 8090:8090
    networks:
      - drill4j-dev-network

  admin-ui:
    image: drill4j/admin-ui:0.5.0-37
    ports:
      - 8091:8080
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network: