version: '3'

services:
  drill-admin:
    image: drill4j/admin:latest
    environment:
      - TEST2CODE_PLUGIN_VERSION=latest
      - LOG_LEVEL=INFO
    ports:
      - 8090:8090
    networks:
      - drill4j-dev-network

  admin-ui:
    image: drill4j/admin-ui:latest
    ports:
      - 8091:8080
    networks:
      - drill4j-dev-network

  example-app:
    image: drill4j/spring-petclinic-sample:0.1.0
    ports:
      - 8087:8080
    environment:
      - JAVA_TOOL_OPTIONS="-agentpath:/data/libdrill_agent.so=drillInstallationDir=/data,adminAddress=host.docker.internal:8090,agentId=ExampleAgent,buildVersion=0.1.0"
    volumes:
      - agents-files:/data

  agents-files:
    image: agents-files:0.5.0
    volumes:
      - agents-files:/agents/java

networks:
  drill4j-dev-network:
    external:
      name: drill4j-dev-network

volumes:
  agents-files: