version: '3'

services:
  drill-admin:
    image: drill4j/admin:0.5.0
    environment:
      - TEST2CODE_PLUGIN_VERSION=0.5.0
      - LOG_LEVEL=INFO
      - DRILL_AGENTS_SOCKET_TIMEOUT=90
    ports:
      - 8090:8090
    networks:
      - drill4j-dev-network
    restart: always

  admin-ui:
    image: drill4j/admin-ui:0.5.0
    ports:
      - 8091:8080
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network:
    external:
      name: drill4j-dev-network